### ISSUE TITLE
SIG: Reload Dispatcher read error

### ISSUE THREAD

**Issue by worxli** [scionproto/scion#2181]
When reloading the SIG with a config file that removes a remote AS, the SIG fails and continuously prints 
```
2018-11-29 15:16:05.939379+0000 [EROR] PktDispatcher: Error reading from connection err=
>  Dispatcher read error
>      read unix @->/run/shm/dispatcher/default.sock: use of closed network connection
```

The reloading logs:
```
2018-11-29 15:16:05.938881+0000 [INFO] Received config reload signal
2018-11-29 15:16:05.939025+0000 [INFO] ReloadConfig: Adding AS... ia=1-ff00:0:111
2018-11-29 15:16:05.939046+0000 [INFO] Updated SIG ia=1-ff00:0:111 sig=1-ff00:0:111,[242.0.0.55]:10081:10080
2018-11-29 15:16:05.939061+0000 [INFO] ReloadConfig: Added AS ia=1-ff00:0:111
2018-11-29 15:16:05.939064+0000 [INFO] ReloadConfig: Adding AS... ia=1-ff00:0:112
2018-11-29 15:16:05.939070+0000 [INFO] Updated SIG ia=1-ff00:0:112 sig=1-ff00:0:112,[242.0.0.71]:10081:10080
2018-11-29 15:16:05.939075+0000 [INFO] ReloadConfig: Added AS ia=1-ff00:0:112
2018-11-29 15:16:05.939079+0000 [INFO] ReloadConfig: Deleting AS... ia=1-ff00:0:110
2018-11-29 15:16:05.939093+0000 [INFO] Removed network ia=1-ff00:0:110 net=242.0.0.32/28
2018-11-29 15:16:05.939101+0000 [DBUG] egress.Session Cleanup: wait for worker ia=1-ff00:0:110 sessId=0x00
2018-11-29 15:16:05.939115+0000 [INFO] EgressWorker: stopping ia=1-ff00:0:110 sessId=0x00
2018-11-29 15:16:05.939167+0000 [DBUG] egress.Session Cleanup: wait for session monitor ia=1-ff00:0:110 sessId=0x00
2018-11-29 15:16:05.939101+0000 [INFO] sigMgr stopping ia=1-ff00:0:110
2018-11-29 15:16:05.939116+0000 [INFO] EgressDispatcher: stopping ia=1-ff00:0:110
2018-11-29 15:16:05.939124+0000 [INFO] Health monitor stopping ia=1-ff00:0:110
2018-11-29 15:16:05.939125+0000 [INFO] sessMonitor: stopped ia=1-ff00:0:110 sessId=0x00
2018-11-29 15:16:05.939227+0000 [DBUG] egress.Session Cleanup: closing conn ia=1-ff00:0:110 sessId=0x00
2018-11-29 15:16:05.939237+0000 [INFO] ReloadConfig: Deleted AS ia=1-ff00:0:110
2018-11-29 15:16:05.939240+0000 [INFO] reloadOnSIGHUP: reload done success=true
```

**Comment by worxli** [comment]
Another one:
```
2018-11-29 16:54:13.734207+0000 [CRIT] Panic msg="runtime error: invalid memory address or nil pointer dereference" stack=
>  goroutine 88 [running]:
>  runtime/debug.Stack(0xc42580dc30, 0xc0f7c0, 0x149bd40)
>  	/usr/local/go/src/runtime/debug/stack.go:24 +0xa7
>  github.com/scionproto/scion/go/lib/log.LogPanicAndExit()
>  	/home/scion/go/src/github.com/scionproto/scion/go/lib/log/log.go:141 +0x6e
>  panic(0xc0f7c0, 0x149bd40)
>  	/usr/local/go/src/runtime/panic.go:491 +0x283
>  github.com/scionproto/scion/go/sig/config.(*Cfg).postprocess(0xc42a15cde0)
>  	/home/scion/go/src/github.com/scionproto/scion/go/sig/config/config.go:54 +0x142
>  github.com/scionproto/scion/go/sig/config.LoadFromFile(0x7fffa8903e86, 0xd, 0x0, 0xc424f8bf50, 0x71bda3)
>  	/home/scion/go/src/github.com/scionproto/scion/go/sig/config/config.go:45 +0x145
>  main.loadConfig(0x7fffa8903e86, 0xd, 0x0)
>  	/home/scion/go/src/github.com/scionproto/scion/go/sig/main.go:184 +0x39
>  main.reloadOnSIGHUP(0x7fffa8903e86, 0xd)
>  	/home/scion/go/src/github.com/scionproto/scion/go/sig/main.go:176 +0xf6
>  created by main.main
>  	/home/scion/go/src/github.com/scionproto/scion/go/sig/main.go:108 +0x5ec
```

**Comment by worxli** [comment]
```
i think we need a bigger fix
for example; if PktDispatcher dies, the sig won't know
that's a bad disconnect
plus, that error should be caught by `reliable.IsDispatcherError`
(i.e. PktDispatcher should use `reliable.IsDispatcherError`, and that function should be extended to cover this case if it does not already)
```
