### ISSUE TITLE
Issues with SCION on 18.04

### ISSUE THREAD

**Issue by klausman** [scionproto/scion#2229]
This is a grab-bag issue that lists things that currently break when trying to use SCION on Ubuntu 18.04.01.

- Python packages may have different hashes for their Py36-compatible packages. This is true for at least cffi.
- Cryptography 1.8.1 doesn't build, 1.8.2 does (but is untested)
- In 18.04.01, using the `_BSD_SOURCE` and `_SVID_SOURCE` in C code will elicit a warning. This breaks at least `zlog` since it compiles with `-Werror`
- zlog has further issues in that `-Werror` activates `-Wnonnull`, which in turn causes failures like these:
```
rule.c: In function ‘zlog_rule_new’:
rule.c:798:8: error: argument 1 null where non-null expected [-Werror=nonnull]
       (strchr(p, 'r') == NULL) || (strchr(p, 's') == NULL)
        ^~~~~~~~~~~~~~
In file included from rule.c:11:0:
/usr/include/string.h:225:14: note: in a call to function ‘strchr’ declared here
 extern char *strchr (const char *__s, int __c)
              ^~~~~~
rule.c:798:36: error: argument 1 null where non-null expected [-Werror=nonnull]
       (strchr(p, 'r') == NULL) || (strchr(p, 's') == NULL)
                                    ^~~~~~~~~~~~~~
In file included from rule.c:11:0:
/usr/include/string.h:225:14: note: in a call to function ‘strchr’ declared here
 extern char *strchr (const char *__s, int __c)
              ^~~~~~
cc1: all warnings being treated as errors
makefile:140: recipe for target 'rule.o' failed
```
This may be fixed (or rather: papered over) by sed'ing the relevant source bits in `env/zlog/deps`:
```
sed -i -e 's/-Werror//g' makefile src/makefile
sed -i -e 's/_BSD_SOURCE/_DEFAULT_SOURCE/g' src/*.c src/*.h
```
- `./scion.sh topology` relies on docker-compose and docker-ce, which are not installed by `env/deps` (this will not be a problem once ZK goes away)
- Th Python tests fail:
```
======================================================================
ERROR: test.lib.main_test.TestMainDefault.test_core_local(True, True, False)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/scion/go/src/github.com/scionproto/scion/python/test/lib/main_test.py", line 104, in _check_core_local
    main_default(core_type, local_type)
  File "/home/scion/go/src/github.com/scionproto/scion/python/lib/main.py", line 72, in main_default
    init_logging(os.path.join(args.log_dir, args.server_id))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not MagicMock

======================================================================
ERROR: test.lib.main_test.TestMainDefault.test_core_local(False, False, True)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/usr/lib/python3.6/unittest/mock.py", line 1179, in patched
    return func(*args, **keywargs)
  File "/home/scion/go/src/github.com/scionproto/scion/python/test/lib/main_test.py", line 104, in _check_core_local
    main_default(core_type, local_type)
  File "/home/scion/go/src/github.com/scionproto/scion/python/lib/main.py", line 72, in main_default
    init_logging(os.path.join(args.log_dir, args.server_id))
  File "/usr/lib/python3.6/posixpath.py", line 80, in join
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not MagicMock

----------------------------------------------------------------------
Ran 769 tests in 7.102s
```

**Comment by jinankjain** [comment]
All of these issues were resolved in #1505

**Comment by matzf** [comment]
This issue (and the linked PR above) can now be closed as this has in the meantime been fixed by  dropping zlog and all the C code, adopting bazel, dropping zookeeper and dropping much of the python code base (in particular @lukedirtwalker's changes in #3457 that also bump the version of the python dependencies).
Installing and building on Ubuntu 18.04 now works like a charm, just following the instructions.

**Comment by lukedirtwalker** [comment]
As @matzf correctly summarized above this is no longer relevant.
