### ISSUE TITLE
sciond exhibits runtime error upon receiving a termination signal

### ISSUE THREAD

**Issue by cmeury** [scionproto/scion#3766]
### Steps to reproduce

1. Run `sciond`
2. Send term signal: `kill -TERM <PID>`

### Observation

* The process terminates with a runtime error (see log output below).
* The behaviour was reproducible.

### Expectation

* The process gracefully terminates.

### Log Output

```
2020-05-13 15:02:40.394299+0000 [INFO] Received signal, exiting... signal=terminated
2020-05-13 15:02:40.394470+0000 [INFO] Shutdown called, waiting a limited amount of time until forceful shutdown time_allowance=5s
2020-05-13 15:02:40.394652+0000 [CRIT] Fatal error err=
>  ListenAndServe error address="127.0.0.1:30255"
>      accept tcp 127.0.0.1:30255: use of closed network connection
2020-05-13 15:02:40.404212+0000 [CRIT] Panic msg="runtime error: invalid memory address or nil pointer dereference" stack=
>  goroutine 1 [running]:
>  runtime/debug.Stack(0xc00027f670, 0xf25be0, 0x1b512a0)
>       /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
>  github.com/scionproto/scion/go/lib/log.HandlePanic()
>       /builds/PRV-PERRIG/scionlab/scion-builder/scion/go/lib/log/log.go:142 +0x6e
>  panic(0xf25be0, 0x1b512a0)
>       /usr/local/go/src/runtime/panic.go:679 +0x1b2
>  github.com/scionproto/scion/go/lib/infra/messenger/tcp.(*Messenger).CloseServer(0xc0001887e0, 0x834239, 0x0)
>       /builds/PRV-PERRIG/scionlab/scion-builder/scion/go/lib/infra/messenger/tcp/messenger.go:213 +0x2a
>  main.realMain(0x0)
>       /builds/PRV-PERRIG/scionlab/scion-builder/scion/go/sciond/main.go:188 +0x1abc
>  main.main()
>       /builds/PRV-PERRIG/scionlab/scion-builder/scion/go/sciond/main.go:69 +0x22
2020-05-13 15:02:40.404354+0000 [CRIT] =====================> Service panicked!
```

### Environment

* `sciond` binary was compiled from commit f756c79
* Running without container.
* OS: 18.04 LTS (Bionic Beaver), GNU/Linux 4.15.0-22-generic

**Comment by Oncilla** [comment]
Hi. Thanks for reporting this.
