### ISSUE TITLE
showpaths runs into nil pointer dereference when probing a path with zero hops

### ISSUE THREAD

**Issue by cmeury** [scionproto/scion#3823]
### Steps to reproduce

1. Run `showpaths -p -dstIA <IA>` with the local IA

### Expectation

The tool handles the edge case gracefully, maybe displaying:

    [ 0] Hops: [] MTU: 0, NextHop: None Status: N/A

### Observation

```
$ showpaths -p -dstIA 16-ffaa:0:1007
Available paths to 16-ffaa:0:1007
2020-07-07 13:20:31.959318+0000 [CRIT] Panic msg="runtime error: invalid memory address or nil pointer dereference" stack=
>  goroutine 1 [running]:
>  runtime/debug.Stack(0xc00023f9e0, 0xb9a140, 0x131abf0)
>  	/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
>  github.com/scionproto/scion/go/lib/log.HandlePanic()
>  	/builds/PRV-PERRIG/scionlab/scion-builder/scion/go/lib/log/log.go:142 +0x6e
>  panic(0xb9a140, 0x131abf0)
>  	/usr/local/go/src/runtime/panic.go:679 +0x1b2
>  github.com/scionproto/scion/go/lib/sciond/pathprobe.PathKey(...)
>  	/builds/PRV-PERRIG/scionlab/scion-builder/scion/go/lib/sciond/pathprobe/paths.go:72
>  github.com/scionproto/scion/go/lib/sciond/pathprobe.Prober.GetStatuses(0x10, 0xffaa00001007, 0x10, 0xffaa00001007, 0xc0000268c8, 0x4, 0x4, 0xd84ea0, 0xc00006c7e0, 0xc0000894f0, ...)
>  	/builds/PRV-PERRIG/scionlab/scion-builder/scion/go/lib/sciond/pathprobe/paths.go:127 +0x3a2
>  main.main()
>  	/builds/PRV-PERRIG/scionlab/scion-builder/scion/go/tools/showpaths/paths.go:102 +0x6f2
2020-07-07 13:20:31.959487+0000 [CRIT] =====================> Service panicked!
```

**Comment by cmeury** [comment]
According to @Oncilla, this was already fixed in https://github.com/scionproto/scion/pull/3784. Closing this issue for now.

**Comment by cmeury** [comment]
Current master just displays `nil` and `timeout` now, which is maybe not beautiful, but also not an exception, so all good from my side.

```
$ bin/showpaths -sciond [127.0.0.60]:30255 -dstIA 1-ff00:0:112 -p
Available paths to 1-ff00:0:112
[ 0] Hops: [] MTU: 1450, NextHop: <nil> Status: Timeout
```
