### ISSUE TITLE
capnp string representation broken on arm32

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#777]
When trying to run the codebase on a 32-bit arm machine, these errors happen every time:

From a RevocationInfo object in a beacon server:

```
Exception in BS._handle_if_timeouts thread:
Traceback (most recent call last):
  File "/home/kormat/scion/lib/thread.py", line 49, in thread_safety_net
    return func(*args, **kwargs)
  File "/home/kormat/scion/infrastructure/beacon_server/base.py", line 718, in _handle_if_timeouts
    self._issue_revocation(if_id, chain)
  File "/home/kormat/scion/infrastructure/beacon_server/base.py", line 611, in _issue_revocation
    self._process_revocation(rev_info, if_id)
  File "/home/kormat/scion/infrastructure/beacon_server/base.py", line 640, in _process_revocation
    logging.info("Processing revocation:\n%s", str(rev_info))
  File "/home/kormat/scion/lib/packet/packet_base.py", line 119, in __str__
    return "%s: %s" % (self.NAME, self.short_desc())
  File "/home/kormat/scion/lib/packet/packet_base.py", line 116, in short_desc
    return str(self.p)
  File "capnp/lib/capnp.pyx", line 1394, in capnp.lib.capnp._DynamicStructBuilder.__str__ (capnp/lib/capnp.cpp:29020)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe0 in position 18: invalid continuation byte
```

From an IFStatePayload object in an edge router:

```
Exception in main process:                                                                                                                                                                                        
Traceback (most recent call last):
  File "/home/kormat/scion/lib/main.py", line 37, in main_wrapper
    main(*args, **kwargs)
  File "/home/kormat/scion/lib/main.py", line 81, in main_default
    inst.run()
  File "/home/kormat/scion/infrastructure/router/main.py", line 180, in run 
    SCIONElement.run(self)
  File "/home/kormat/scion/infrastructure/scion_elem.py", line 399, in run 
    self._packet_process()
  File "/home/kormat/scion/infrastructure/scion_elem.py", line 465, in _packet_process
    self.handle_request(*self._in_buf.get(timeout=1.0))
  File "/home/kormat/scion/infrastructure/router/main.py", line 709, in handle_request
    handler(pkt, from_local_as)
  File "/home/kormat/scion/infrastructure/router/main.py", line 402, in process_path_mgmt_packet
    str(mgmt_pkt.get_payload()))
  File "/home/kormat/scion/lib/packet/packet_base.py", line 119, in __str__
    return "%s: %s" % (self.NAME, self.short_desc())
  File "/home/kormat/scion/lib/packet/packet_base.py", line 116, in short_desc
    return str(self.p)
  File "capnp/lib/capnp.pyx", line 1394, in capnp.lib.capnp._DynamicStructBuilder.__str__ (capnp/lib/capnp.cpp:29020)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x85 in position 88: invalid start byte
```

**Comment by scrye** [comment]
This was specific to the Python code, which we no longer support any more. Closing this.
