### ISSUE TITLE
python socket code doesn't handle dispatcher exiting

### ISSUE THREAD

**Issue by kormat** [scionproto/scion#974]
Steps to reproduce:
```
./scion.sh run
./test/integration/end2end_test.py # works fine
./supervisor/supervisor.sh stop dispatcher
$ test/integration/end2end_test.py
2017-02-21 16:10:25.509117+00:00 [INFO] (End2End 1-11 > 1-12 main) Testing: 1-11 -> 1-12
2017-02-21 16:10:25.519033+00:00 [WARNING] (End2End 1-11 > 1-12 main) Connect error: [Errno 2] No such file or directory
2017-02-21 16:10:25.525308+00:00 [WARNING] (Elem.packet_recv) Connect error: [Errno 2] No such file or directory
2017-02-21 16:10:25.525507+00:00 [WARNING] (End2End 1-11 > 1-12 main) Connect error: [Errno 2] No such file or directory
2017-02-21 16:10:25.626537+00:00 [CRITICAL] (End2End 1-11 > 1-12 main) Exception in main process:
2017-02-21 16:10:25.628006+00:00 [CRITICAL] (End2End 1-11 > 1-12 main) Traceback (most recent call last):
2017-02-21 16:10:25.628493+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)   File "/home/kormat/go/src/github.com/netsec-ethz/scion/lib/main.py", line 37, in main_wrapper
2017-02-21 16:10:25.628911+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)     main(*args, **kwargs)
2017-02-21 16:10:25.629297+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)   File "test/integration/end2end_test.py", line 128, in main
2017-02-21 16:10:25.629670+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)     retries=args.retries).run()
2017-02-21 16:10:25.630044+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)   File "/home/kormat/go/src/github.com/netsec-ethz/scion/test/integration/base_cli_srv.py", line 289, in run
2017-02-21 16:10:25.630448+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)     self._run()
2017-02-21 16:10:25.630828+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)   File "/home/kormat/go/src/github.com/netsec-ethz/scion/test/integration/base_cli_srv.py", line 313, in _run
2017-02-21 16:10:25.631203+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)     if not self._run_test(src, dst):
2017-02-21 16:10:25.631582+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)   File "/home/kormat/go/src/github.com/netsec-ethz/scion/test/integration/base_cli_srv.py", line 326, in _run_test
2017-02-21 16:10:25.631960+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)     client = self._create_client(data, finished, src, dst, server.sock.port)
2017-02-21 16:10:25.632331+00:00 [CRITICAL] (End2End 1-11 > 1-12 main) AttributeError: 'ReliableSocket' object has no attribute 'port'
2017-02-21 16:10:25.632746+00:00 [CRITICAL] (End2End 1-11 > 1-12 main)
2017-02-21 16:10:25.633087+00:00 [CRITICAL] (End2End 1-11 > 1-12 main) Exiting
```

**Comment by kormat** [comment]
The warnings give no useful context, and the code shouldn't cause an exception like that.

**Comment by shitz** [comment]
The infrastructure now handles the dispatcher disappearing and reappearing.
